README.md
=> cmake .. does not refer to chemfiles folder

CMakeLists.txt, doc/overview.rst, include/chemfiles.h, include/chemfiles/Atom.hpp, include/chemfiles/formats/PDB.hpp, include/chemfiles/selections/expr.hpp, src/Atom.cpp, src/Frame.cpp, src/capi/atom.cpp, src/formats/PDB.cpp, src/formats/XYZ.cpp, src/selections/expr.cpp, src/selections/parser.cpp, tests/atoms.cpp, tests/c/atom.c, tests/c/frame.c, tests/c/selections.c, tests/c/trajectory.c, tests/formats/pdb.cpp, tests/parser.cpp, tests/selections.cpp, tests/topology.cpp
In the `Atom` class:
-  `name_` to `element_`
- add `label_`, and modified/added corresponding functions/operators.
In PDB.cpp
- read `label` and construct Atom object with both `element_` and `label_`
Then added corresponding tests in tests/atoms.cpp
------
TODO: 
- check it.
- Replace `name` by `element` in the rest of the project.
=> Initial commit to include "label" variable in Atom class

include/chemfiles/files/NcFile.hpp, src/files/NcFile.cpp, src/formats/NcFormat.cpp, tests/formats/amber-netcdf.cpp
This should fix #45. 
@pgbarletta, is it possible for you to send me a file without Unit Cell information, so that I can add a test here?
=> Check for unit cell presence in NetCDF format

.gitmodules, tests/CMakeLists.txt, tests/c/logging.c, tests/c/trajectory.c, tests/files/basic-file.cpp, tests/files/ncfile.cpp, tests/files/tng-file.cpp, tests/formats/amber-netcdf.cpp, tests/formats/dcd-molfile.cpp, tests/formats/gro-molfile.cpp, tests/formats/lammps-molfile.cpp, tests/formats/pdb.cpp, tests/formats/tng.cpp, tests/formats/trr-molfile.cpp, tests/formats/xtc-molfile.cpp, tests/formats/xyz.cpp, tests/frame.cpp, tests/trajectory.cpp
=> Remove the git submodule

CMakeLists.txt, Doxyfile, appveyor.yml, include/chemfiles.h, include/chemfiles.hpp, include/chemfiles/Logger.hpp, include/chemfiles/UnitCell.hpp, include/chemfiles/config.in.hpp, include/chemfiles/files/NcFile.hpp, include/chemfiles/formats/NcFormat.hpp, src/FormatFactory.cpp, src/capi/atom.cpp, src/capi/cell.cpp, src/capi/frame.cpp, src/capi/logging.cpp, src/capi/residue.cpp, src/capi/selection.cpp, src/capi/topology.cpp, src/capi/trajectory.cpp, src/files/NcFile.cpp, src/formats/NcFormat.cpp, src/utils.cpp, tests/external/helpers/helpers.cpp, tests/files/ncfile.cpp, tests/formats/amber-netcdf.cpp
=> Enable testing on mingw-w64

src/formats/XYZ.cpp, tests/formats/xyz.cpp
=> Write name in XYZ format rather than type

src/formats/PDB.cpp, tests/formats/pdb.cpp
=> Respecting PDB standard for atom with more than 4 connections

README.md
Pretty good job already. I just moved some things around a bit. Some questions/tips:
- use this product template (https://github.com/zalando/zalando-howto-open-source/blob/master/producttemplate.md) or something similar to assess your audience and then bring some of the user more into the README. Especially:
- why would I use this?
- is this different/better/newer/simpler than similar tools out there? Or are there no similar tools like it (which could be a good thing to mention)?
- how has this helped you and/or others work faster/more effectively/more simply?
- how do you quantify the words you use to "sell" Chemfiles: "Modern" (compared to what?); "easy-to-use" (because of its object-oriented nature? what does that actually *look* like, concretely, such that it's easy to use?)
- why …
=> Feedmereadmes edit of README

CHANGELOG.md, doc/src/capi/chfl_residue.rst, include/chemfiles/capi/residue.h, src/capi/residue.cpp, tests/capi/doc/chfl_residue/atoms.c, tests/capi/residue.cpp
=> Add chfl_residue_atoms

CHANGELOG.md, README.md, doc/src/formats.rst, external/CMakeLists.txt, include/chemfiles/formats/Molfile.hpp, src/FormatFactory.cpp, src/formats/Molfile.cpp, tests/CMakeLists.txt, tests/external/helpers.cpp, tests/external/helpers.hpp, tests/formats/lammps-molfile.cpp, tests/formats/mol2-molfile.cpp, tests/formats/molden-molfile.cpp, tests/formats/tng.cpp, tests/formats/trr-molfile.cpp
This is surprisingly difficult, due to the varying adherence to the molfile API from the plugins.
=> Activate more molfiles plugins

README.md, doc/src/formats.rst, include/chemfiles/formats/SDF.hpp, src/FormatFactory.cpp, src/formats/SDF.cpp, tests/CMakeLists.txt, tests/formats/sdf.cpp
Still need to add support for atomic properties, which are supported by this format.
I'll update the test URL once it's been merged.
=> Initial SDF Support

CHANGELOG.md, doc/src/capi/chfl_residue.rst, include/chemfiles/Residue.hpp, include/chemfiles/capi/atom.h, include/chemfiles/capi/frame.h, include/chemfiles/capi/residue.h, src/Residue.cpp, src/capi/residue.cpp, src/formats/MMTF.cpp, src/formats/PDB.cpp, tests/capi/doc/chfl_residue/property.c, tests/capi/residue.cpp, tests/doc/residue/property.cpp, tests/formats/mmtf.cpp, tests/formats/pdb.cpp
Maybe this is better as an atom property, but the chainid is generally regarded as a residue property (for example, how the MMTF data structure is ordered).
=> Residue properties

include/chemfiles/formats/Molfile.hpp, src/formats/Molfile.cpp, tests/formats/dcd-molfile.cpp, tests/formats/lammps-molfile.cpp
And this is why you should never merge your own code ...
=> Fix double add to the frame cache in Molfile::read_step

CHANGELOG.md, README.md, doc/src/formats.rst, include/chemfiles/formats/CSSR.hpp, include/chemfiles/utils.hpp, src/FormatFactory.cpp, src/formats/CSSR.cpp, tests/CMakeLists.txt, tests/formats/cssr.cpp
This builds on top of #158, and should be merged after it.
~~TODO: doc & changleog~~
=> Add CSSR file format support

.travis.yml, appveyor.yml, external/CMakeLists.txt, scripts/ci/build-docs.sh, tests/CMakeLists.txt, tests/external/helpers.cpp, tests/external/helpers.hpp, tests/formats/gro.cpp, tests/formats/pdb.cpp
Concerning the PDB test: on my machine, removing just the test that creates 100000+ atoms bring the run time under valgrind fromp 400s to 120s. Removing track-origins bring it to 60s.
=> Various CI fixes and improvements

src/formats/MMTF.cpp, tests/CMakeLists.txt, tests/formats/mmtf.cpp
Store the alternative locations of atoms in MMTF structures.
=> Alternative location support in MMTF

cmake/CompilerFlags.cmake, include/chemfiles/capi/topology.h, include/chemfiles/files/GzFile.hpp, include/chemfiles/files/XzFile.hpp, include/chemfiles/formats/MMTF.hpp, include/chemfiles/misc.hpp, include/chemfiles/selections/expr.hpp, include/chemfiles/selections/lexer.hpp, include/chemfiles/selections/parser.hpp, src/Configuration.cpp, src/Frame.cpp, src/capi/topology.cpp, src/files/GzFile.cpp, src/files/PlainFile.cpp, src/files/XzFile.cpp, src/formats/CSSR.cpp, src/formats/GRO.cpp, src/formats/MMTF.cpp, src/formats/MOL2.cpp, src/formats/SDF.cpp, src/formats/XYZ.cpp, src/selections/expr.cpp, src/selections/lexer.cpp, src/selections/parser.cpp
(this is based on top of #180, I will rebase when the other one is merged)
=> Various cleanup tasks

doc/src/properties.rst, src/formats/PDB.cpp, tests/formats/pdb.cpp
The first commit is self-explanatory.
The second is a bit more controversial. I added the ability to change the topology based on a given property.  I am wondering if this should be done in a more general sense (IE not just the `altloc` property).
=> Improved PDB Support

src/File.cpp
This is a better fix for #203, completely removing the use of exceptions here.
=> Do not use execptions when reading line by line

include/chemfiles/Atom.hpp, include/chemfiles/Frame.hpp, include/chemfiles/Property.hpp, include/chemfiles/Residue.hpp, src/Atom.cpp, src/Frame.cpp, src/Property.cpp, src/Residue.cpp, src/formats/GRO.cpp, src/formats/MOL2.cpp, src/formats/PDB.cpp, src/formats/SDF.cpp, src/formats/mmCIF.cpp, tests/atoms.cpp, tests/doc/atom/property.cpp, tests/doc/frame/get.cpp, tests/doc/residue/property.cpp, tests/frame.cpp, tests/residue.cpp
This allows for cleaner code in formats, when getting properties of a specific type.
=>  Add an API to get property only if it has a given type 

include/chemfiles/capi/atom.h, include/chemfiles/capi/residue.h, include/chemfiles/shared_allocator.hpp, tests/shared_allocator.cpp
I wrote this while trying to fix the Windows tests for Chemfiles.jl. 
I found a bug in shared_alloc, which means we will want to do a 0.9.1 release with this patch.
=> Fix bug in shared_allocator

include/chemfiles/formats/PDB.hpp, src/formats/MOL2.cpp, src/formats/PDB.cpp, src/formats/SDF.cpp, tests/CMakeLists.txt, tests/formats/pdb.cpp, tests/formats/sdf.cpp
- Fixed a bug in reading PDB X coordinate
- Fixed a bug in reading PDB residues
- Fixed a bug when a MOL2 file does not begin with @TRIPOS<MOLECULE>
- Added support for SDF charges
=> Misc fixes

.travis.yml, CMakeLists.txt, cmake/chemfiles-config.cmake.in
They where missing the INTERFACE_INCLUDE_DIRECTORIES property for some reason.
Fix #251
=> Fix cmake imported target files

.travis.yml, AUTHORS, CMakeLists.txt, README.md, cmake/chemfiles-config.cmake.in, include/chemfiles/formats/PDB.hpp, include/chemfiles/formats/TNG.hpp, src/formats/MOL2.cpp, src/formats/PDB.cpp, src/formats/SDF.cpp, src/formats/TNG.cpp, tests/CMakeLists.txt, tests/formats/pdb.cpp, tests/formats/sdf.cpp, tests/formats/tng.cpp
Backports of #248 #249 and #252 to 0.9
=> Backports to 0.9

README.md, doc/src/formats.rst, doc/src/properties/atom.toml, doc/src/properties/frame.toml, include/chemfiles/Connectivity.hpp, include/chemfiles/formats/SMI.hpp, src/FormatFactory.cpp, src/formats/SMI.cpp, tests/CMakeLists.txt, tests/formats/smi.cpp
Warning: this code is a bit rough and fairly difficult to read. It will need to be refactored and all I can really guarantee is that is won't crash - probably.
Write support is terrible as it cannot current write rings, this will need to be fixed before it is merged.
Fixes #241
=> Initial SMI support

doc/conf.py.in, examples/c/generate.c, examples/c/indexes.c, examples/c/select.c, include/chemfiles/formats/Molfile.hpp, src/FormatFactory.cpp
Cf the two commits, nothing groundbreaking here =)
=> Small fixes

CHANGELOG.md, include/chemfiles/Trajectory.hpp, src/Trajectory.cpp, tests/factory.cpp
=> fix(trajectory): do not allow reading frames in append mode

CMakeLists.txt, scripts/ci/setup-travis.sh, tests/CMakeLists.txt
Some linux distributions use `LIB_INSTALL_DIR`/`INCLUDE_INSTALL_DIR` to change the install path. So accept these =)
=> Cmake install improvements

include/chemfiles/formats/SMI.hpp, src/formats/SMI.cpp, tests/CMakeLists.txt, tests/formats/smi.cpp
This PR will address issues #303 and #255. The first issue is described by the inability of the SMILES parser to read CurlySMILES as well as an issue reading bonds. The second issue is addressed by a single line. For #255, the SMILES writer has been reworked to longer be recursive and new test cases have been added to ensure that it functions properly.
=> Fix Issues #303 and #255

CHANGELOG.md, src/Format.cpp, src/files/GzFile.cpp, tests/CMakeLists.txt, tests/files/gz-file.cpp, tests/formats/compressed-xyz.cpp
Currently it is not allowed to append to .gz files.
This change feels too easy, but tests work :D
=> feat: allow appending to gz files

doc/src/selections.rst, src/selections/expr.cpp, tests/selection.cpp
=> Check residue properties for selections

doc/src/properties/residue.toml, include/chemfiles/formats/MMTF.hpp, src/formats/MMTF.cpp, tests/CMakeLists.txt, tests/formats/mmtf.cpp
Everything is implemented except for adding symmetric bonds.
=> Add symmetry operations to MMTF

CHANGELOG.md, Doxyfile.in, doc/conf.py.in, doc/ext/chfl_example.py, doc/ext/chfl_selection.py, doc/src/selections.rst, doc/static/css/chemfiles.css, include/chemfiles/selections/expr.hpp, include/chemfiles/selections/parser.hpp, src/formats/GRO.cpp, src/formats/MMTF.cpp, src/parse.cpp, src/selections/expr.cpp, src/selections/parser.cpp, tests/capi/frame.cpp, tests/selection.cpp, tests/selections/parser.cpp, tests/selections/selections-utils.cpp
Fixes #327 
Ping @dkonstan, since you were interested in using this. You should be able to compile this branch and use the code with Julia if you want to test before the next release.
TODO:
=> Allow to use sub-selection in numerical functions (distance/angle/...)

include/chemfiles/UnitCell.hpp, src/UnitCell.cpp
Fixes https://github.com/chemfiles/chemfiles/issues/354
=> Fix spelling of “orthorhombic” Fixes #354

doc/src/devdoc/file.rst, doc/src/devdoc/format.rst, include/chemfiles/Format.hpp, include/chemfiles/formats/CIF.hpp, include/chemfiles/formats/CSSR.hpp, include/chemfiles/formats/MOL2.hpp, include/chemfiles/formats/PDB.hpp, include/chemfiles/formats/TRR.hpp, include/chemfiles/formats/XTC.hpp, include/chemfiles/formats/mmCIF.hpp
The most relevant one is pointing people to TextFormat in addition to Format.
=> Small updates to internal documentation

doc/src/installation.rst
=> Clarify static lib and header installation from binaries

.travis.yml, doc/CMakeLists.txt, doc/Doxyfile.in, doc/conf.py.in, doc/requirements.txt, scripts/ci/build-docs.sh, scripts/ci/setup-travis.sh
In particular, require a more recent doxygen version to ensure `^^` is interpreted as a newline in aliases
=> Update documentation requirements

src/files/TNGFile.cpp, src/formats/MMTF.cpp, src/formats/PDB.cpp
Now that I have access to these compilers again, I can check that the code keeps compiling with them =)
=> Small fixes for compiling with PGI and intel

include/chemfiles/capi/misc.h, include/chemfiles/capi/shared_allocator.hpp, include/chemfiles/capi/types.h, src/UnitCell.cpp, src/capi/misc.cpp, src/capi/trajectory.cpp, tests/capi/shared_allocator.cpp, tests/cell.cpp, tests/doc/capi/chfl_formats_list.c
=> Backport to 0.10

.travis.yml, cmake/CompilerFlags.cmake, scripts/ci/setup-travis.sh
Required to update https://github.com/chemfiles/chemfiles.js to v0.10
=> Update emscripten configuration for Emscripten 2

CHANGELOG.md, include/chemfiles/Property.hpp, src/Property.cpp, tests/atoms.cpp, tests/capi/atom.cpp, tests/capi/frame.cpp, tests/capi/residue.cpp, tests/frame.cpp, tests/lints/check-capi-docs.py, tests/lints/check-error-messages.py, tests/lints/check-public-headers.py, tests/property.cpp, tests/residue.cpp
Properties are now stored inside a `std::map`, which guarantee a fixed iteration order over them (they will be sorted according to the property name). This removes a source of non determinism in code and written files
=> Guarantee fixed iteration order over properties

CHANGELOG.md, doc/src/capi/misc.rst, doc/src/classes/misc.rst, doc/src/properties/frame.toml, include/chemfiles/FormatFactory.hpp, include/chemfiles/Trajectory.hpp, include/chemfiles/capi/misc.h, include/chemfiles/files/NcFile.hpp, include/chemfiles/formats/AmberNetCDF.hpp, include/chemfiles/misc.hpp, src/FormatFactory.cpp, src/Trajectory.cpp, src/capi/misc.cpp, src/files/NcFile.cpp, src/formats/AmberNetCDF.cpp, src/formats/LAMMPSData.cpp, tests/capi/misc.cpp, tests/doc/capi/chfl_guess_format.c, tests/doc/guess_format.cpp, tests/factory.cpp, tests/files/netcdf-file.cpp, tests/formats/amber-netcdf.cpp, tests/formats/amber-restart.cpp, tests/formats/lammps-data.cpp, tests/lints/check-capi-docs.py, tests/trajectory.cpp
=> Backports to release-0.10

CHANGELOG.md, doc/src/properties/residue.toml, external/CMakeLists.txt, include/chemfiles/formats/Molfile.hpp, src/FormatFactory.cpp, src/FormatMetadata.cpp, src/formats/Molfile.cpp, tests/CMakeLists.txt, tests/factory.cpp, tests/formats/psf-molfile.cpp
Temporary solution to #208.
~This is based on top of #422, which contains changes to the VMD molfile code, I'll rebase once it has been merged.~
=> PSF reader based on VMD molfile

include/chemfiles/formats/TPR.hpp, src/formats/DCD.cpp, tests/CMakeLists.txt, tests/formats/dcd.cpp
Fixes https://github.com/chemfiles/Chemfiles.jl/issues/69
=> Fix wrong conversion for angles in triclinic DCD files

src/formats/PDB.cpp
=> Fix PDB reading error message

src/formats/XYZ.cpp, tests/formats/xyz.cpp
=> Read Lattice in extended XYZ even if Properties is missing

CHANGELOG.md, include/chemfiles/formats/TPR.hpp, src/formats/TPR.cpp, tests/CMakeLists.txt, tests/formats/tpr.cpp
=> Fix TPR reader for v2025
