chemfiles/chemfiles

- CHANGELOG.md
- doc/selections.rst
- include/chemfiles/Atom.hpp
- include/chemfiles/Frame.hpp
- include/chemfiles/UnitCell.hpp
- include/chemfiles/optional.hpp
- include/chemfiles/selections/expr.hpp
- include/chemfiles/selections/lexer.hpp
- src/Atom.cpp
- src/Topology.cpp
- src/formats/Molfile.cpp
- src/formats/PDB.cpp
- src/selections/expr.cpp
- src/selections/parser.cpp
- tests/atoms.cpp
- tests/parser.cpp
- tests/selections.cpp
This use the new label field in more places:
- For atoms without an element name (f080248d55e64531d7a53528352183a4f1cd08b7);
- In molfiles-based formats (ae4b117c513b0b90cc7c4eae43a0ce1b441785de);
- In selections (a8e1e79c3079d97a0c570522f08af45d887910c3).
@pgbarletta I commited the CHANGELOG update (07b96d00aa70b74d99e3143ca2d73abf0fcd4f97) using your username, are you OK with it? Do the other changes seems fine to you?
Follow #41.
> More 'labels' usage

- CHANGELOG.md
- doc/overview.rst
- doc/selections.rst
- include/chemfiles.h
- include/chemfiles/Atom.hpp
- include/chemfiles/selections/expr.hpp
- include/chemfiles/types.hpp
- src/Atom.cpp
- src/Frame.cpp
- src/capi/atom.cpp
- src/formats/PDB.cpp
- src/formats/TNG.cpp
- src/formats/XYZ.cpp
- src/selections/expr.cpp
- src/selections/parser.cpp
- tests/CMakeLists.txt
- tests/atoms.cpp
- tests/c/atom.c
- tests/c/frame.c
- tests/c/selections.c
- tests/c/trajectory.c
- tests/formats/pdb.cpp
- tests/formats/tng.cpp
- tests/parser.cpp
- tests/selections.cpp
- tests/topology.cpp
Some work to make the atoms/residues more usable
- b828926 removes the `Atom::type`, which was not used anywhere;
- 778cf74 rename `label => name` and `element => type`. @pgbarletta, what do you think of this? This match the naming of PDB and TNG formats, and looks like it is also the names used in most software.
- 1831d4a and  0e2c384 add `resname` and `resid` selections.
Also @pgbarletta if/when you update to the this version, take care that the order of parameters of `Atom` constructor where inverted.
> Residues, part n+1

- CHANGELOG.md
- doc/selections.rst
- include/chemfiles/selections/lexer.hpp
- src/selections/expr.cpp
- src/selections/lexer.cpp
- src/selections/parser.cpp
- tests/parser.cpp
Using `$1`, `$2`, `$3` will lead to errors when passing selections as strings in a shell script. This replace them by the `#1`, `#2`, `#3` syntax.
I am opening this as a pull request to gather feedback on the change. I'll merge this PR later in the week.
> Change the selections variables syntax

- src/Atom.cpp
- tests/atoms.cpp
We already normalize 2 letters atomic types when looking for atomic properties: `Atom("ZN")` and `Atom("zN")` use the Zinc atomic data.
This introduce the same normalization for 1 letter atomic type, so that `Atom("C")` and `Atom("c")` are the same thing.
@pgbarletta, do you think we should do this? It feels more coherent to me.
> Also normalize 1-letter atomic type

- CHANGELOG.md
- doc/src/capi/chfl_property.rst
- include/chemfiles/Property.hpp
- include/chemfiles/capi/property.h
- src/capi/property.cpp
- src/formats/PDB.cpp
- tests/capi/doc/chfl_property/kind.c
- tests/capi/property.cpp
- tests/property.cpp
This means that instead of writing
```cpp
auto property = Property(...);
try {
auto value = property.as_double();
} catch (const PropertyError&) {
// ...
} 
```
one can write simpler code as
```cpp
auto property = Property(...);
if (property.get_kind() == Property::DOUBLE) {
auto value = property.as_double();
} else {
// ...
} 
```
This will be handy for the dynamic languages binding of property, allowing to directly extract a property value without checking for all possible kinds.
> Allow to access Property kind

- include/chemfiles/formats/PDB.hpp
From https://github.com/chemfiles/chemfiles/issues/113
Well, an almost embarrasing PR.
> Switched residues_ type from std::unordered_map to std::map.

- .travis.yml
- include/chemfiles/Property.hpp
- include/chemfiles/unreachable.hpp
- include/chemfiles/utils.hpp
- scripts/ci/check-public-headers.py
- src/UnitCell.cpp
- src/selections/lexer.cpp
This should prevent accidental pollution.
> Ensure that only whitelisted headers can be included in the public interface

- include/chemfiles/Connectivity.hpp
- src/Connectivity.cpp
- src/Topology.cpp
- tests/frame.cpp
- tests/topology.cpp
Removing an atom might shift other atomic indexes, we need to account for that and shift the bonds accordingly
> Fix bonds indexes after removing an atom

- CHANGELOG.md
- include/chemfiles/Configuration.hpp
- include/chemfiles/FormatFactory.hpp
- include/chemfiles/generic.hpp
- include/chemfiles/mutex.hpp
- src/Configuration.cpp
- src/FormatFactory.cpp
- src/generic.cpp
There are three global state points in the code, two are user-visible:
- the Configuration class;
- the warning system;
- the FormatFactory class; 
This PR make all of the thread-safe by wrapping the accessed data inside a mutex.
> Make global state thread safe

- doc/src/devdoc/contributing.rst
- doc/src/devdoc/internals.rst
- include/chemfiles/Format.hpp
- include/chemfiles/FormatFactory.hpp
- include/chemfiles/formats/AmberNetCDF.hpp
- include/chemfiles/formats/LAMMPSData.hpp
- include/chemfiles/formats/Molfile.hpp
- include/chemfiles/formats/PDB.hpp
- include/chemfiles/formats/TNG.hpp
- include/chemfiles/formats/Tinker.hpp
- include/chemfiles/formats/XYZ.hpp
- src/FormatFactory.cpp
- src/formats/AmberNetCDF.cpp
- src/formats/LAMMPSData.cpp
- src/formats/Molfile.cpp
- src/formats/PDB.cpp
- src/formats/TNG.cpp
- src/formats/Tinker.cpp
- src/formats/XYZ.cpp
- tests/factory.cpp
The goal of this PR is to allow (1) discovery of format names instead of needing to get back to the doc every time and (2) help with format name usage, specifically with typos.
The first commit implement suggestion like `not format named 'lammpsdata'. did you mean 'LAMMPS Data'?`. The following commits export format metadata for use by external tools.
This metadata is not part of the main API, and as such is not exported to C. If you need to use it from other languages than C++, please ask!
> Allow external code to acess Format metadata

- include/chemfiles/utils.hpp
- src/Selection.cpp
- src/formats/PDB.cpp
- src/formats/Tinker.cpp
- src/formats/XYZ.cpp
- src/selections/lexer.cpp
- src/selections/parser.cpp
- tests/formats/tinker.cpp
- tests/formats/xyz.cpp
- tests/selections/lexer.cpp
Instead of relying on stringstreams, which are way slower.
On my system, this speeds up the following code from 0.38s to 0.27s
```cpp
#include <chemfiles.hpp>
using namespace chemfiles;
int main() {
auto trajectory = Trajectory("tests/data/xyz/water.xyz");
for (size_t i = 0; i<trajectory.nsteps(); i++) {
auto frame = trajectory.read_step(i);
}
for (size_t i = 0; i<trajectory.nsteps(); i++) {
auto frame = trajectory.read_step(i);
}
for (size_t i = 0; i<trajectory.nsteps(); i++) {
auto frame = trajectory.read_step(i);
}
for (size_t i = 0; i<trajectory.nsteps(); i++) {
auto frame = trajectory.read_step(i);
}
}
```
> Use sscanf when reading free form text formats

- include/chemfiles/UnitCell.hpp
- include/chemfiles/types.hpp
- src/UnitCell.cpp
- tests/cell.cpp
- tests/doc/cell/matrix.cpp
- tests/types.cpp
I decided not to implement `Matrix3D operator*=(Matrix3D)` as this requires a copy of the matrix to be made and I feel compound assignment operators should be free of coping. Other than that, I feel this closes #162.
> Matrix update

- CHANGELOG.md
- doc/src/capi/chfl_frame.rst
- include/chemfiles/Frame.hpp
- include/chemfiles/capi/frame.h
- src/Frame.cpp
- src/capi/frame.cpp
- tests/capi/doc/chfl_frame/guess_bonds.c
- tests/capi/frame.cpp
- tests/doc/frame/guess_bonds.cpp
- tests/frame.cpp
It makes more sense, now that the topology contains more than just bonds.
> Rename Frame::guess_topology to Frame::guess_bonds

- CHANGELOG.md
- include/chemfiles/capi/atom.h
- include/chemfiles/capi/cell.h
- include/chemfiles/capi/frame.h
- include/chemfiles/capi/property.h
- include/chemfiles/capi/residue.h
- include/chemfiles/capi/selection.h
- include/chemfiles/capi/topology.h
- include/chemfiles/capi/trajectory.h
- include/chemfiles/shared_allocator.hpp
- src/capi/atom.cpp
- src/capi/cell.cpp
- src/capi/frame.cpp
- src/capi/property.cpp
- src/capi/residue.cpp
- src/capi/selection.cpp
- src/capi/topology.cpp
- src/capi/trajectory.cpp
- src/shared_allocator.cpp
- tests/capi/doc/chfl_frame/guess_bonds.c
- tests/capi/doc/chfl_residue/for_atom.c
- tests/capi/doc/chfl_residue/from_topology.c
- tests/capi/doc/chfl_topology/from_frame.c
- tests/capi/doc/chfl_topology/residues_linked.c
- tests/capi/frame.cpp
- tests/capi/residue.cpp
- tests/capi/topology.cpp
- tests/capi/trajectory.cpp
This allow users of the C API to directly access data inside frames/topologies. This allow to remove a copy on read access, and two copies on write access.
The core of the code is in shared_allocator.hpp, a singleton class allowing to allocate/deallocate pointers with shared pointers semantics. Specifically, the aliasing constructor of `std::shared_ptr<t>`
(`std::shared_ptr<T>(std::shared_ptr<U>&, T*)`) is emulated by storing an atomic reference count for all allocated pointers.
`std::shared_ptr` itself was also considered, but the different solutions had various shortcomings:
- define `CHFL_ATOM` as `std::shared_ptr<Atom>`, and pass around `CHFL_ATOM*`, allocating shared pointers on the heap. This fails to encode const relations between pointers, for example accessing the topology of a …
> Use a shared allocator for C API pointers

- include/chemfiles/unreachable.hpp
A macro could clash with external macros definitions
> Make unreachable a [[noreturn]] function

- src/formats/MMTF.cpp
- tests/CMakeLists.txt
- tests/formats/mmtf.cpp
I've added a few new features to the MMTF format. They are:
- Ability to read from GZ and XZ files.
- Now we save the formal charge of atoms in a given residue.
- Biologic assemblies identified in the MMTF file are saved as residue properties.
> Additional MMTF support

- doc/requirements.txt
Sphinx v1.8.0 launched today around noon. Apparently, there is a bug in this version that causes the documentation build for Chemfiles to fail. I am forcing the Sphinx version to be set at 1.7.9.
Note: I have not submitted a bug upstream, but we should consider doing so.
> Set Sphinx version to avoid bug in 1.8.0

- include/chemfiles/shared_allocator.hpp
- src/shared_allocator.cpp
- tests/capi/doc/chfl_frame/guess_bonds.c
- tests/capi/frame.cpp
Some of these appear when using chemfiles from multiple threads at once, which is the case by default of Rust tests.
> Fix mutliple bugs in shared allocator

- doc/src/properties/atom.toml
- doc/src/properties/frame.toml
- doc/src/properties/residue.toml
- include/chemfiles/formats/PDB.hpp
- include/chemfiles/formats/mmCIF.hpp
- src/formats/MMTF.cpp
- src/formats/PDB.cpp
- src/formats/mmCIF.cpp
- tests/CMakeLists.txt
- tests/formats/mmcif.cpp
- tests/formats/mmtf.cpp
- tests/formats/pdb.cpp
The purpose of this PR is a few fold:
> Additional PDB fixes

- .travis.yml
- include/chemfiles/formats/LAMMPSData.hpp
- include/chemfiles/utils.hpp
- scripts/ci/lint-code.py
- src/formats/GRO.cpp
- src/formats/LAMMPSData.cpp
- src/formats/MOL2.cpp
- src/formats/PDB.cpp
- src/formats/SDF.cpp
- src/formats/Tinker.cpp
- src/formats/XYZ.cpp
- src/formats/mmCIF.cpp
- src/selections/lexer.cpp
- tests/CMakeLists.txt
- tests/formats/lammps-data.cpp
- tests/utils.cpp
This PR came from an issue where converting LAMMPS Data to PDB would create a warning about residue id 18446744073709551615 (size_t(-1)).
So the commits fix the LAMMPS Data reader wrt molecule id, and force usage of the same function for all parsing of string to numeric types, checking that the parsed value fit in the given type.
> Improve residue id handling

- include/chemfiles/selections/expr.hpp
- src/Selection.cpp
- src/selections/expr.cpp
Sub selections (the `name O` in `is_bonded(#1, name O)` where evaluated at every call to is_match, which is once by atom/bond/pairs in the system depending on the selection context.
This PR adds a way for selection element to cache data (more specifically a way to know when to clear the cached data), and uses it for sub selections.
On a test locally using [cfiles](https://github.com/chemfiles/cfiles), this makes the time for hydrogen bonds detection in a small trajectory go from 172s to 60s (almost three time faster!!) for the `name O and is_bonded (#1, name C) and is_bonded (#1, name H)` selection.
> Add a cache for sub-selections

- src/formats/PDB.cpp
- tests/formats/pdb.cpp
There's a problem in how the atom type in PDB files was being read. This leads to a confusion between CA (as in alpha-carbon) and Ca (as in calcium). Below is a quick fix.
Previously, the additional test failed as the mass of an alpha carbon was 40!
> Fix PDB atom type issue

- README.md
See #126. Not a big issue, but I'm just getting started and the first thing I tried didn't work.
> fix(README): replace outdated method in example

- include/chemfiles/formats/TNG.hpp
- src/formats/TNG.cpp
- tests/formats/tng.cpp
At the moment only the box is converted from nm to angtrom. However all length dependent units should be converted. Especially positions and velocities.
Furthermore TNG does not always use nm. In fact one could specify an arbitrary exponent for length units. This is handled by these changes.
Relevant GROMACS source: https://github.com/gromacs/gromacs/blob/ac628532b96f338ace10fb78a01d47e109b81bb8/src/gromacs/fileio/tngio.cpp#L1258-L1283
**TODO:**
> fix(tng): Correct Conversion of Length Units

- tests/external/helpers.cpp
- tests/formats/xtc.cpp
Unfortunately this breaks tests for mmcif format. The test file contains the correct entries like `_cell.length_a`, but chemfiles only seems to parse deprecated entries `_cell_length_a`.
Don't really know how to fix this easily, because I've never used this format :(
> fix(tests): missing fabs in approx_eq

- src/formats/CSSR.cpp
- src/formats/GRO.cpp
- src/formats/MMTF.cpp
- src/formats/MOL2.cpp
- src/formats/PDB.cpp
- src/formats/XYZ.cpp
- src/formats/mmCIF.cpp
There is no need to resize frames when reading to them, a new frame is created in Trajectory::read anyway.
> Do not resize frames to 0 when reading

- include/chemfiles/formats/MMTF.hpp
- src/formats/MMTF.cpp
- tests/formats/mmtf.cpp
The code made a few assumption on what data was present in the frame, assumptions only matched by files containing biomolecular systems.
In particular, atoms are not guaranteed by chemfiles to be ordered inside residues, and not all atoms have associated residues.
@frodofine I would appreciate if you could give this a look! If you don't have time, that's fine, just let me know 😃
> Fix MMTF writer for non-biological systems

- src/formats/MMTF.cpp
- tests/CMakeLists.txt
- tests/formats/mmtf.cpp
Before:
```
$ time ./mmtf
[chemfiles] MMTF Writer: atom name 'C23456' is too long for MMTF format, it will be truncated
[chemfiles] MMTF Writer: atom type 'HuuuuH' is too long for MMTF format, it will be truncated
===============================================================================
All tests passed (117 assertions in 2 test cases)
./mmtf  785.46s user 0.25s system 99% cpu 13:05.78 total
```
After:
```
$ time ./mmtf
[chemfiles] MMTF Writer: atom name 'C23456' is too long for MMTF format, it will be truncated
[chemfiles] MMTF Writer: atom type 'HuuuuH' is too long for MMTF format, it will be truncated
===============================================================================
All tests passed (117 assertions in 2 test cases)
./mmtf  1.79s user 0.28s system 99% cpu 2.067 total …
```
> Improve speed of MMTF parsing for global bonds

- tests/lints/check-capi-docs.py
- tests/lints/check-error-messages.py
- tests/lints/check-public-headers.py
- tests/lints/check-used-functions.py
This is the only way to specify the encoding parmeter with Python2.
The encoding parameter is needed else Python uses the locale to guess the encoding. For LANG=C, this means using ascii encoding and thus having "UnicodeDecodeError: 'ascii' codec can't decode byte ..." exceptions.
> Use codecs.open to read files with python

- src/UnitCell.cpp
- tests/cell.cpp
I noticed that infinite cells are not persistent when writing and then reading .gro files.
This is because we [write zeros](https://github.com/chemfiles/chemfiles/blob/master/src/formats/GRO.cpp#L227) for infinite cells. But when reading we find 3 values and construct a unit cell from those values. The result is an orthorhombic cell with lengths zero. This breaks distances and other stuff.
I guess it would be good to also handle setter functions similar (as described in #69) in the long run.
> fix(UnitCell): constructing infinite cell from zero lengths

- include/chemfiles/capi/utils.hpp
- include/chemfiles/error_fmt.hpp
- include/chemfiles/warnings.hpp
- src/formats/MMTF.cpp
- src/warnings.cpp
- tests/capi/utils.cpp
Related to #303. The first examples now properly fails with `SMI Reader: unknown symbol: '{'`.
> Small fixes related to exceptions at the C APi boundary

- include/chemfiles/Residue.hpp
- include/chemfiles/sorted_set.hpp
- src/Connectivity.cpp
- src/Residue.cpp
- src/Topology.cpp
Instead of checking each residue to find if the removed atom was inside, directly remove the atom from the corresponding residue
> Speed up atom removal in large structures

- src/formats/SDF.cpp
- src/formats/SMI.cpp
- tests/formats/sdf.cpp
- tests/formats/smi.cpp
While I was at, I also changed the few remaining tests using boost::fs to loop over 'bad' files, and found one case of broken error message.
> Fix a segfault in SMI reader

- include/chemfiles/files/NcFile.hpp
- src/files/NcFile.cpp
- src/formats/AmberNetCDF.cpp
- tests/CMakeLists.txt
- tests/files/netcdf-file.cpp
- tests/formats/amber-netcdf.cpp
Found some old script that uses `scale_factor` in NetCDF extensively. This PR implements scaling of cell lengths, angles, coordinates and velocities by `scale_factor`.
Fixes #268.
> feat: NetCDF scale factor

- include/chemfiles/capi/trajectory.h
- src/capi/trajectory.cpp
- tests/capi/trajectory.cpp
- tests/doc/capi/chfl_trajectory/memory_buffer.c
- tests/doc/capi/chfl_trajectory/path.c
All the other functions make a copy of the string (chfl_atom_name, chfl_selection_string), this one did it differently for no good reason (it is not a performance sensitive function)
> Unify chfl_trajectory_path with other functions getting string values

- .travis.yml
- src/formats/PDB.cpp
- tests/CMakeLists.txt
- tests/formats/pdb.cpp
Turns out the fix is really simple. The way to misrepresent PDB files will never cease to amaze me!
> Check to ensure end IDs are greater than start IDs in the PDB reader

- CHANGELOG.md
- doc/src/capi/chfl_frame.rst
- doc/src/capi/chfl_topology.rst
- include/chemfiles/capi/frame.h
- include/chemfiles/capi/topology.h
- src/capi/frame.cpp
- src/capi/topology.cpp
- tests/capi/frame.cpp
- tests/capi/topology.cpp
- tests/doc/capi/chfl_frame/clear_bonds.c
- tests/doc/capi/chfl_topology/clear_bonds.c
They are part of the public C++ API, so I think they should be part of the public C API too. No idea why they were left out initially.
> Expose {Frame,Topology}::clear_bonds to the C API

- doc/src/properties/residue.toml
- src/Frame.cpp
- tests/frame.cpp
The code would return NaN if atoms `i, k, m` were colinear. I think 0 is a much more reasonable value here
> Fix Frame::out_of_plane for co-linear atoms

- CMakeLists.txt
- cmake/CompilerFlags.cmake
- include/chemfiles/UnitCell.hpp
- include/chemfiles/config.in.h
- include/chemfiles/files/Bz2File.hpp
- src/files/Bz2File.cpp
- src/utils.cpp
Instead of relying on cmake to set `CHEMFILES_WINDOWS`, set it in `include/chemfiles/config.h` when installing the library.
This should fix #333.
> Make sure CHEMFILES_WINDOWS is defined on chemfiles installation

- include/chemfiles/Residue.hpp
- include/chemfiles/capi/residue.h
- include/chemfiles/formats/GRO.hpp
- include/chemfiles/formats/MOL2.hpp
- include/chemfiles/formats/PDB.hpp
- include/chemfiles/formats/mmCIF.hpp
- include/chemfiles/parse.hpp
- src/Residue.cpp
- src/Topology.cpp
- src/capi/residue.cpp
- src/formats/GRO.cpp
- src/formats/LAMMPSData.cpp
- src/formats/MMTF.cpp
- src/formats/MOL2.cpp
- src/formats/Molfile.cpp
- src/formats/PDB.cpp
- src/formats/mmCIF.cpp
- src/parse.cpp
- tests/capi/residue.cpp
- tests/doc/capi/chfl_residue/id.c
- tests/formats/gro.cpp
- tests/formats/pdb.cpp
- tests/parse.cpp
This PR stops the PDB writer from writing `CONECT` records for standard residues and writes `TER` records at the end of chains. It also attempts to convert some large residue IDs to see if they are actually negative numbers.
> PDB Write changes

- src/formats/MMTF.cpp
- src/formats/Molfile.cpp
While debugging for #344, I added the assertions below. I think they are a nice additional safety guard to have regardless of how we end up resolving the issue.
> Add some assertions to the MMTF reader

- src/Connectivity.cpp
- src/formats/MMTF.cpp
This makes reading 3j3q.mmtf file 30% faster, and completely remove MMTFFormat::apply_symmetry from a callgrind profile.
There is no need to update the angles if we are only accessing the bonds (which are always up to date).
Thanks @sguionni for reporting that reading this was slow!
> Do not update Topology angles/dihedrals on bond access

- src/Frame.cpp
- tests/frame.cpp
fix #301
Instead of changing the criterion for all atoms as in #315, the same criterion is kept but the radii of C/O/H/N/S/F are changed.
This should make the code working while we look for a better bond perception algorithm
> More conservative fix for bonds detection

- src/File.cpp
- tests/files/bz2-file.cpp
- tests/files/gz-file.cpp
- tests/files/memory-file.cpp
- tests/files/plain-file.cpp
- tests/files/xz-file.cpp
- tests/formats/cssr.cpp
Currently one is able to write multiple frames to CSSR files. Chemfiles is able to read back only one and I guess the standard allows only one frame anyway. This is because the checks rely on the cursor position which is currently not updated when writing. So one can write multiple frames without triggering those checks.
Technically this also applies for appending, but this would require an implementation of `tell` for all different files. Since CSSR does not support appending (and it would not be sensible to support appending for any other one-frame format) we can safely ignore appending for now.
> fix(file): update position of cursor when writing

- .travis.yml
- scripts/ci/setup-travis.sh
It is much slower than other builders for an unknown reason
> Speedup OS X gcc CI build by not re-installing everything

- src/selections/parser.cpp
- tests/selections/parser.cpp
> Set higher precedence for 'not' than 'and'/'or' in selections

- include/chemfiles/capi/trajectory.h
- include/chemfiles/files/Bz2File.hpp
- include/chemfiles/files/GzFile.hpp
- include/chemfiles/files/MemoryBuffer.hpp
- include/chemfiles/files/XzFile.hpp
- src/Trajectory.cpp
- src/capi/trajectory.cpp
- src/files/Bz2File.cpp
- src/files/GzFile.cpp
- src/files/MemoryBuffer.cpp
- src/files/MemoryFile.cpp
- src/files/XzFile.cpp
- tests/capi/trajectory.cpp
- tests/files/bz2-file.cpp
- tests/files/gz-file.cpp
- tests/files/memory-file.cpp
- tests/files/xz-file.cpp
Fixes #378 
This ensures (a) that the size of the buffer is the actual amount of data written to it and no longer the available capacity; and (b) that the buffer is always NULL terminated
> Rewrite the MemoryBuffer class

- doc/conf.py.in
- include/chemfiles/formats/MMTF.hpp
- src/formats/MMTF.cpp
- tests/CMakeLists.txt
- tests/formats/mmtf.cpp
I have not read the full spec but these examples [[1]](https://github.com/rcsb/mmtf/blob/master/spec.md#chainspermodel) [[2]](https://github.com/rcsb/mmtf/blob/master/spec.md#groupsperchain) indicate that chains and groups are indexed consecutively. This is also aparent when looking at [`StructureData::print`](https://github.com/rcsb/mmtf-cpp/blob/ee4b855cf53b4a3ee7a40cc62d57195875fe84a5/include/mmtf/structure_data.hpp#L1028). When skipping, chemfiles wrongfully starts at 0 again for every model.
Fixes #344.
> fix(mmtf): chain and group indices are consecutive

- src/UnitCell.cpp
- tests/cell.cpp
Fixes #384 by rejecting unit cells that are not diagonal and orthorhombic. This means orthorhombic UnitCells can be constructed from diagonal matrices only.
> fix: reject rotated orthorhombic cell matrices

- include/chemfiles/capi/misc.h
- include/chemfiles/capi/shared_allocator.hpp
- include/chemfiles/capi/types.h
- src/capi/misc.cpp
- src/capi/trajectory.cpp
- tests/capi/shared_allocator.cpp
- tests/doc/capi/chfl_formats_list.c
The main one is the second commit, using `chfl_free` instead of `free` to manage memory for the format metadata list.
> More updates for 0.10

- CHANGELOG.md
- doc/src/capi/misc.rst
- doc/src/classes/misc.rst
- include/chemfiles/Atom.hpp
- include/chemfiles/Error.hpp
- include/chemfiles/FormatFactory.hpp
- include/chemfiles/Frame.hpp
- include/chemfiles/Trajectory.hpp
- include/chemfiles/capi/misc.h
- include/chemfiles/capi/types.h
- include/chemfiles/capi/utils.hpp
- include/chemfiles/error_fmt.hpp
- include/chemfiles/misc.hpp
- src/FormatFactory.cpp
- src/Trajectory.cpp
- src/capi/misc.cpp
- tests/capi/misc.cpp
- tests/capi/utils.cpp
- tests/doc/capi/chfl_guess_format.c
- tests/doc/guess_format.cpp
- tests/factory.cpp
- tests/lints/check-capi-docs.py
- tests/trajectory.cpp
This will be used in the javascript bindings for 0.10 to decide when to use "native" in memory IO or write the file to a temporary in-memory filesystem and read/write from there.
@frodofine or @ezavod do you have some time to give this a look in the next week?
> Add a guess_format function returning the format we would use for a given filename

- CHANGELOG.md
- doc/src/properties/frame.toml
- include/chemfiles/files/NcFile.hpp
- include/chemfiles/formats/AmberNetCDF.hpp
- src/FormatFactory.cpp
- src/files/NcFile.cpp
- src/formats/AmberNetCDF.cpp
- src/formats/LAMMPSData.cpp
- tests/files/netcdf-file.cpp
- tests/formats/amber-netcdf.cpp
- tests/formats/amber-restart.cpp
- tests/formats/lammps-data.cpp
This enables chemfiles to read and write Amber Restart (.ncrst) files. Those files are pretty similar to Amber Trajectory files but use mostly doubles and contain only a single frame.
Closes #47.
Additional:
- ~fix link to specs of .gro files~
- added check in LAMMPS Data tests for writing multiple frames (see #352)
- read and write frame title property of Amber formats
> Implement Amber Restart Format

- src/formats/LAMMPSTrajectory.cpp
- tests/formats/lammps-trajectory.cpp
Read per-atom properties (see discussion in #409). LAMMPS cannot store any frame properties, so nothing to do here. Also, all LAMMPS fixes, computes, or variables are either integer or double. Reading string properties is only a fallback if something went wrong, e.g. when dealing with incorrect user-generated data or upstream changes in LAMMPS.
Array data is written element-wise which means that a 3D property results in 3 scalar properties `myProp[I]` where `I = 1, 2, 3`.
Edit: Tests failing due to changes in #412. Waiting for these changes to be merged and then run tests again.
<details>
<summary>How to generate test input</summary>
```
variable x index 1
variable y index 1
variable z index 1
variable   t index 300
variable xx equal 10*$x
variable yy equal 10*$y
variable zz equal 10*$z …
```
> Read Arbitrary Per-Atom Properties in LAMMPS Atoms Format

- include/chemfiles/capi/misc.h
- include/chemfiles/misc.hpp
We can now read the file in guess_format when trying to distinguish between formats with the same extension.
This is a follow-up to #407.
> Update guess_format documentation

- doc/src/installation.rst
Instead point users to https://github.com/chemfiles/chemfiles-prebuilt. While OpenSuse build service is awesome, building chemfiles on it is taking much longer in each release than I have the energy and time to deal with. 
Users needing access to the prebuilt C++ library should use conda instead, or download it from https://github.com/chemfiles/chemfiles-prebuilt.
> Remove the Linux binary from OpenSuse from the documentation

- CHANGELOG.md
- include/chemfiles/Atom.hpp
- src/capi/atom.cpp
- src/formats/CML.cpp
- src/formats/XYZ.cpp
- tests/atoms.cpp
- tests/doc/atom/properties.cpp
This makes the per-atom property map an optional field. Some (most?) formats don't make use of per-atom properties. Allocating the map for every atom nonetheless comes with quite some overhead. This is noticeable for frames with many atoms especially.
When reading 'ubiquitin.xtc' a ~11% speedup is observable (cf. [comparison to other implementations](https://github.com/chemfiles/benchmarks)).
For a `.nc` file with 50k atoms the speedup is ~19% for reading and ~7% for writing.
Ideally, this can be superseded by a more data-oriented approach as in #288.
This changes the user-facing API.
<details>
<summary>Benchmarking</summary>
R/W 1k steps with 50k atoms as `.nc` from C++ in a `tmpfs` ramdisk.
```
Benchmark 1: ./bench_write
Time (mean ± σ):     11.704 s ±  0.325 s    [User: 8.692 s, …
```
> refactor(Atom): do not allocate map without atom properties

- include/chemfiles/external/span.hpp
- include/chemfiles/files/BinaryFile.hpp
- src/files/BinaryFile.cpp
- src/files/Netcdf3File.cpp
- src/formats/CML.cpp
- tests/files/binary-files.cpp
I'm currently in the process of rewriting the XTC and TRR parser based on the new `BinaryFile`.
While doing so, I couldn't reach the _writing_ speed obtained with `xdrfile`.
These formats frequently write large chunks of data (e.g. the position array) at once.
Before this PR, this involved a lot of overhead for swapping and writing individual values.
By using a buffer for swapping and writing, these chunks can be written at once without that much overhead.
For XTC/TRR it's also helpful to skip larger chunks of data without parsing it and to get the file size.
This PR introduces two functions for that in `BinaryFile`.
Besides this, there are also some misc changes:
- Some minor adaptations in the CML parser and `span`.
- Use the new skip function to skip the padding in NetCDF files.
- Fix …
> refactor(BinaryFile): swap and write binary data in buffered chunks

- .github/workflows/docs.yml
- doc/requirements.txt
This was lost in the migration to Github action (#394)
> Re-enable automatic deployment of nightly documentation

- doc/ext/chfl_selection.py
- doc/src/properties/frame.toml
- examples/c/indexes.c
- include/chemfiles/Format.hpp
- include/chemfiles/external/string_view.hpp
- src/Format.cpp
- src/formats/DCD.cpp
- src/formats/LAMMPSTrajectory.cpp
- tests/formats/lammps-trajectory.cpp
- tests/parse.cpp
- tests/selection.cpp
This fixes #442 by adding the frame property `is_unwrapped` to the LAMMPS trajectory reader. This boolean property is always set when reading.
Also, this fixes #398 (at least for text files) by advancing the cursor before reading (and parsing) of a frame. It's possible to read the next frame after an (parsing) exception, as long as the initial scanning of frame offsets works without an error.
As stated in the issue, I think this is most important for text files because they can be easily edited by hand which may introduce inconsistencies.
Additionally, there are some minor changes to suppress compiler warnings. Notably, Clang doesn't like the string literal `_sv`, so this option is disabled in the cmake config.
> Fix cursor position in text files and add unwrapped property to LAMMPS

- CHANGELOG.md
- doc/src/properties/atom.toml
- doc/src/properties/frame.toml
- include/chemfiles/files/BinaryFile.hpp
- include/chemfiles/files/XDRFile.hpp
- include/chemfiles/formats/TPR.hpp
- include/chemfiles/formats/TRR.hpp
- include/chemfiles/formats/XTC.hpp
- src/FormatFactory.cpp
- src/files/XDRFile.cpp
- src/formats/TPR.cpp
- src/formats/TRR.cpp
- src/formats/XTC.cpp
- tests/CMakeLists.txt
- tests/files/xdr-file.cpp
- tests/formats/tpr.cpp
This somewhat completes my journey through the GROMACS binary formats and is the last format needed to easily deal with GROMACS simulation output.
TPR files are preprocessed topology files which are generated from TOP and ITP files (see #212) and are needed to actually run a simulation. Therefore one has typically TPR files easier at hand than TOP files e.g. on hpc systems.
Unfortunately, TPR files are not really meant for use outside GROMACS which may lead to unannounced changes in the format (see e.g. [this issue](https://gitlab.com/gromacs/gromacs/-/issues/3269) from a few years back). The tests (and possibly implementation) should be regularly amended by TPRs from the latest release to see if anything has changed.
However, MDAnalysis parses TPR as well which means there are multiple …
> feat: TPR reader

- src/files/BinaryFile.cpp
The issue was discovered as part of https://github.com/JuliaPackaging/Yggdrasil/pull/5339
> Improve endianness detection for aarch64-linux-musl

- .github/MinGW-Toolchain.cmake
- .github/workflows/docs.yml
- .github/workflows/tests.yml
This tries to make CI a bit faster (MinGW builder takes 25 min just to compile the code, vs 6-8 min on most other builders)
> Make MinGW builder faster on CI

- CHANGELOG.md
- src/formats/TPR.cpp
- tests/CMakeLists.txt
- tests/formats/tpr.cpp
Removes warning the warning "file version is from the future" when reading TPR files produced by GROMACS version 2023.
Also, added test files.
> Add TPR files with format version 2023

- CHANGELOG.md
- src/files/XDRFile.cpp
- tests/CMakeLists.txt
- tests/files/xdr-file.cpp
This PR adds faster decoding of integers which are stored as <= 64 bits. For these values, integer arithmetic can be used as proposed [here](https://doi.org/10.1186/s13104-021-05536-5) and implemented by [libxtc](https://gitlab.com/impulse_md/libxtc).
libxtc also has a special implementation for larger ints using 128 bit ints. I found that these lengths are rather unusual in "typical" MD trajectories.
Instead, the old algorithm is used to decode those values here eliminating special compile time checks for the presence of 128 bit types.
Also, a testcase for these large ints is added to test the old code paths.
The changes reduce the time to read the `ubuquitin.xtc` test file by more than 20%.
> Faster XTC decoding

- src/formats/MMTF.cpp
Writing a mmtf file of a big molecule is taking a lot of time abnormally.
On line 593 of src/formats/MMTF.cpp there is the line :
`auto positions = frame.positions();`
This affectation make a copy of the whole position vector instead of just got a reference.
Because this affectation is called for every residue, it dramatically slow down the writing process.
Changing it to
`const auto& positions = frame.positions();`
will use a reference assignment and correct the optimization issue.
> mmtf optimization issue

- include/chemfiles/formats/LAMMPSData.hpp
- include/chemfiles/utils.hpp
- src/formats/LAMMPSData.cpp
- tests/CMakeLists.txt
- tests/formats/lammps-data.cpp
Fix #485 
Corresponding test file: https://github.com/chemfiles/tests-data/blob/1256f2dbf7370528fb8361b28d78e4534633b1f7/lammps-data/whitespaces.lmp
> Handle whitespaces in more places in LAMMPS Data format

- doc/src/properties/frame.toml
- include/chemfiles/formats/AmberNetCDF.hpp
- src/formats/AmberNetCDF.cpp
- tests/formats/amber-netcdf.cpp
- tests/formats/amber-restart.cpp
1. I’ve added support for reading simulation time from both Amber Restart and Amber NetCDF trajectories. I also added some checks for this in the existing tests. I also did some manual testing with a handful of other `.nc` files to confirm the reported times are accurate - though it wasn’t particularly exhaustive. Reading NetCDF trajectories without time info still works as expected too.
2. I’ve also added the ability to write simulation time for both Amber Restart and Amber NetCDF trajectories. For trajectories, time writing is only initialized if the first frame written includes time info. If a later frame includes time info but time writing wasn’t initialized, a warning is raised, and the time isn’t written. If time writing *is* initialized and a frame doesn’t have time info, nothing …
> Support for reading and writing simulation time in Amber Restart and Amber NetCFD trajectories

- CHANGELOG.md
- include/chemfiles/error_fmt.hpp
- include/chemfiles/files/XDRFile.hpp
- include/chemfiles/formats/XTC.hpp
- src/File.cpp
- src/files/XDRFile.cpp
- src/formats/TPR.cpp
- src/formats/TRR.cpp
- src/formats/XTC.cpp
- src/formats/XYZ.cpp
- src/selections/expr.cpp
- tests/CMakeLists.txt
- tests/files/xdr-file.cpp
- tests/formats/xtc.cpp
Fixes #479.
I faked a test XTC file for reading, but properly testing writing is really hard because single frames can become rather large.
Instead of testing writing of the new XTC format directly, the underlying compression functions are tested in the XDR file tests.
> Add support for XTC format for gigantic systems

- include/chemfiles/files/BinaryFile.hpp
- src/files/BinaryFile.cpp
We now load/unload 100MiB chunks, making sure loading large files don't fill up memory and leave some for processing of the data.
xref https://github.com/chemfiles/Chemfiles.jl/issues/83
> Limit memory used by BinaryFile to 100MiB in mmap mode
